export const ALL_FILTERS = 'ALL_FILTERS';
export const CURRENT_FILTER = 'CURRENT_FILTER';
export const ASYNC_ADD_TICKETS = 'ASYNC_ADD_TICKETS';
export const ERROR_500_SERVER = 'ERROR_500_SERVER';
export const ERROR_DATA_EMPTY = 'ERROR_DATA_EMPTY';
export const LOADING_DATA = 'LOADING_DATA';
export const FILTER_TICKETS = 'FILTER_TICKETS';
export const FILTER_BEST_TICKETS = 'FILTER_BEST_TICKETS';
